// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * CollectionGateway handles collection data storage and retrieval.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../../internal/models/models.js";

/**
 * LoadCollections returns all stored collections.
 */
export function LoadCollections(): $CancellablePromise<models$0.Service[] | null> {
    return $Call.ByID(3045186535);
}

/**
 * SaveCollections persists collections.
 */
export function SaveCollections(collections: models$0.Service[] | null): $CancellablePromise<models$0.Service[] | null> {
    return $Call.ByID(3769559432, collections);
}
