// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../../internal/models/models.js";

export function AddHistory(entry: models$0.HistoryEntry): $CancellablePromise<models$0.HistoryEntry> {
    return $Call.ByID(2542561263, entry);
}

export function ClearHistory(): $CancellablePromise<void> {
    return $Call.ByID(2795171465);
}

export function GetHistory(limit: number, offset: number): $CancellablePromise<models$0.HistoryEntry[] | null> {
    return $Call.ByID(1949932450, limit, offset);
}
