// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SecretsGateway handles secure storing, listing, and removing of workspace secrets.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

/**
 * AddSecret saves the secret value securely and appends the key name to the list of secret keys.
 */
export function AddSecret(key: string, value: string): $CancellablePromise<string[] | null> {
    return $Call.ByID(1998728562, key, value);
}

/**
 * DeleteSecret removes the secret from the keyring and removes its key name from the configuration list.
 */
export function DeleteSecret(key: string): $CancellablePromise<string[] | null> {
    return $Call.ByID(2849628360, key);
}

/**
 * GetSecret retrieves the decrypted secret value from the keyring.
 */
export function GetSecret(key: string): $CancellablePromise<string> {
    return $Call.ByID(1565580709, key);
}

/**
 * GetSecrets returns a list of all defined secret keys.
 */
export function GetSecrets(): $CancellablePromise<string[] | null> {
    return $Call.ByID(3159177186);
}
