// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ServiceGateway handles service and Git repository management operations.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../../internal/models/models.js";

/**
 * CommitGit commits uncommitted changes to the Git repository.
 */
export function CommitGit(directory: string, message: string): $CancellablePromise<void> {
    return $Call.ByID(3199452776, directory, message);
}

/**
 * GetGitStatus retrieves the Git status of the specified directory.
 */
export function GetGitStatus(directory: string): $CancellablePromise<models$0.GitStatus> {
    return $Call.ByID(3675291507, directory);
}

/**
 * ImportCurl imports endpoints into a service from a cURL command.
 */
export function ImportCurl(serviceId: string, curlCommand: string): $CancellablePromise<models$0.Service> {
    return $Call.ByID(2555662018, serviceId, curlCommand);
}

/**
 * ImportService imports a service from the specified directory.
 */
export function ImportService(directory: string): $CancellablePromise<models$0.Service> {
    return $Call.ByID(2809845691, directory);
}

/**
 * ImportSwagger imports a service definition from a Swagger/OpenAPI file.
 * The frontend passes (name string, filePath string) where filePath may be a URL or file path.
 */
export function ImportSwagger(name: string, filePath: string): $CancellablePromise<models$0.Service> {
    return $Call.ByID(2278652028, name, filePath);
}

/**
 * InitGit initializes a Git repository in the directory.
 */
export function InitGit(directory: string, remoteUrl: string): $CancellablePromise<void> {
    return $Call.ByID(457563701, directory, remoteUrl);
}

/**
 * LoadServices returns all stored services.
 */
export function LoadServices(): $CancellablePromise<models$0.Service[] | null> {
    return $Call.ByID(1936763405);
}

/**
 * PullGit pulls from the remote Git repository.
 */
export function PullGit(directory: string): $CancellablePromise<void> {
    return $Call.ByID(1407890882, directory);
}

/**
 * PushGit pushes commits to the remote Git repository.
 */
export function PushGit(directory: string): $CancellablePromise<void> {
    return $Call.ByID(2446111983, directory);
}

/**
 * SaveServices persists services with an optional commit message.
 */
export function SaveServices(services: models$0.Service[] | null, commitMessage: string): $CancellablePromise<models$0.Service[] | null> {
    return $Call.ByID(3981719628, services, commitMessage);
}

/**
 * SyncGit synchronizes the Git repository (pull then push).
 */
export function SyncGit(directory: string): $CancellablePromise<void> {
    return $Call.ByID(428274582, directory);
}

/**
 * TestPreflightConfig runs a test for the given preflight configuration.
 */
export function TestPreflightConfig(config: models$0.PreflightConfig | null): $CancellablePromise<string> {
    return $Call.ByID(1105996134, config);
}
