// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SettingsGateway handles user settings and tab state operations.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as importlib$0 from "../../internal/import/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../../internal/models/models.js";

/**
 * LoadSettings loads the user settings.
 */
export function LoadSettings(): $CancellablePromise<importlib$0.UserSettings> {
    return $Call.ByID(543554622);
}

/**
 * LoadTabState loads the tab state.
 */
export function LoadTabState(): $CancellablePromise<models$0.TabState | null> {
    return $Call.ByID(2755824159);
}

/**
 * SaveSettings saves the user settings.
 */
export function SaveSettings(settings: importlib$0.UserSettings): $CancellablePromise<void> {
    return $Call.ByID(2360693435, settings);
}

/**
 * SaveTabState saves the tab state.
 */
export function SaveTabState(state: models$0.TabState | null): $CancellablePromise<void> {
    return $Call.ByID(285348974, state);
}

/**
 * UpdateTheme updates the user's theme in the settings file.
 */
export function UpdateTheme(theme: string): $CancellablePromise<void> {
    return $Call.ByID(2442564067, theme);
}
