// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * VersionGateway exposes endpoint version history (stored in SQLite) to the
 * frontend. serviceId is accepted for introspection/debugging only — versions
 * are keyed by endpointId.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../../internal/models/models.js";

/**
 * AddEndpointVersion creates a new version (version = MAX+1), stores it, then
 * prunes the oldest so only the newest maxVersions remain (FIFO).
 */
export function AddEndpointVersion(serviceId: string, endpointId: string, config: models$0.RequestConfig, maxVersions: number): $CancellablePromise<models$0.EndpointVersion> {
    return $Call.ByID(1304009412, serviceId, endpointId, config, maxVersions);
}

/**
 * ClearEndpointVersions deletes all versions for an endpoint (used on endpoint
 * deletion).
 */
export function ClearEndpointVersions(serviceId: string, endpointId: string): $CancellablePromise<void> {
    return $Call.ByID(3426531963, serviceId, endpointId);
}

/**
 * GetEndpointVersions returns the newest `limit` versions for an endpoint,
 * ordered newest-first.
 */
export function GetEndpointVersions(serviceId: string, endpointId: string, limit: number): $CancellablePromise<models$0.EndpointVersion[] | null> {
    return $Call.ByID(3942415282, serviceId, endpointId, limit);
}
