// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as http$0 from "../../../net/http/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../time/models.js";

export interface Auth {
    "type": AuthType;
    "basicUsername"?: string;
    "basicPassword"?: string;
    "bearerToken"?: string;
    "apiKeyKey"?: string;
    "apiKeyValue"?: string;

    /**
     * "header" or "query"
     */
    "apiKeyAddTo"?: string;
}

export interface AuthConfig {
    "type": string;
    "active": boolean;
    "basicUser": string;
    "basicPass": string;
    "bearerToken": string;
    "apiKeyName": string;
    "apiKeyValue": string;
    "apiKeyLocation": string;
}

export enum AuthType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    AuthNone = "none",
    AuthBasic = "basic",
    AuthBearer = "bearer",
    AuthAPIKey = "apikey",
};

export interface Cookie {
    "name": string;
    "value": string;
    "path": string;
    "domain": string;
    "expires": string;
    "maxAge": number;
    "secure": boolean;
    "httpOnly": boolean;
}

export interface Endpoint {
    "id": string;
    "serviceId": string;
    "name": string;
    "method": string;
    "url": string;
    "authenticated": boolean;
    "authType": string;
    "metadata": EndpointMetadata;
    "params": Param[] | null;
    "headers": Header[] | null;
    "body": string;
    "preflight"?: PreflightConfig | null;
    "lastVersion": number;
    "versions": EndpointVersion[] | null;
}

export interface EndpointMetadata {
    "version": string;
    "lastUpdated": number;
}

export interface EndpointVersion {
    "version": number;
    "config": RequestConfig;
    "lastUpdated": number;
}

export interface EnvironmentConfig {
    "name": string;
    "isUnsafe": boolean;
    "variables": Variable[] | null;
}

export interface FormDataItem {
    "key": string;
    "value": string;
    "type": FormDataType;
    "filePath"?: string;
}

export enum FormDataType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    FormDataTypeText = "text",
    FormDataTypeFile = "file",
};

export interface GitStatus {
    "isGit": boolean;
    "remoteUrl": string;
    "branch": string;
    "hasUncommittedChanges": boolean;
    "hasUnpushedCommits": boolean;
    "lastSync": number;
}

export type Header = NameValue;

export interface HistoryEntry {
    "id": string;
    "serviceId"?: string | null;
    "endpointId"?: string | null;
    "method": string;
    "url": string;
    "requestHeaders": Header[] | null;
    "requestBody": string;
    "responseStatus": number;
    "responseStatusText": string;
    "responseHeaders": Header[] | null;
    "responseBody": string;
    "timeElapsed": number;
    "size": number;
    "createdAt": string;
}

export interface NameValue {
    "name": string;
    "value": string;
    "enabled": boolean;
    "secretKey"?: string;
    "type": string;
}

export type Param = NameValue;

export interface PreflightConfig {
    "request": Request | null;

    /**
     * "body" or "header"
     */
    "tokenLocation": string;

    /**
     * JSON key path or header key name
     */
    "tokenPath": string;

    /**
     * Header name to write (defaults to "Authorization")
     */
    "tokenHeader": string;

    /**
     * Prefix (e.g. "Bearer ")
     */
    "tokenPrefix": string;
    "cacheKey"?: string;
    "cacheTtl"?: time$0.Duration;

    /**
     * JSON key path for expiry
     */
    "expiryPath"?: string;

    /**
     * "expires_in", "epoch", "epoch_ms", "iso8601"
     */
    "expiryType"?: string;
}

export interface Request {
    "method": string;
    "url": string;
    "headers": { [_ in string]?: string } | null;
    "queryParams": { [_ in string]?: string } | null;
    "pathParams": { [_ in string]?: string } | null;
    "auth"?: Auth | null;

    /**
     * "none", "raw", "form-data", "urlencoded", "binary"
     */
    "bodyType": string;
    "bodyRaw": string;
    "bodyForm": { [_ in string]?: string } | null;
    "bodyFormData": FormDataItem[] | null;
    "bodyBinary": string | null;
    "timeout": time$0.Duration;
    "followRedirects": boolean | null;
    "insecureSkipVerify": boolean;
    "proxyUrl": string;
    "preflight"?: PreflightConfig | null;
}

export interface RequestConfig {
    "method": string;
    "url": string;
    "authenticated": boolean;
    "authType": string;
    "params": Param[] | null;
    "headers": Header[] | null;
    "body": string;
    "preflight"?: PreflightConfig | null;
}

export interface Response {
    "contentType": string;
    "timeTaken": time$0.Duration;
    "requestHeaders": http$0.Header;
    "responseHeaders": http$0.Header;
    "statusCode": number;
    "statusText": string;
    "bodyBytes": string | null;
    "size": number;
    "cookies": Cookie[] | null;
    "body": string;
    "error"?: string | null;
}

export interface Service {
    "id": string;
    "name": string;
    "environments": EnvironmentConfig[] | null;
    "isAuthenticated": boolean;
    "authType"?: AuthType | null;
    "auth"?: AuthConfig | null;
    "preflight"?: PreflightConfig | null;
    "endpoints": Endpoint[] | null;
    "directory": string;
    "selectedEnvironment"?: string | null;
    "gitUrl"?: string | null;
}

export interface ServiceStub {
    "id": string;
    "name": string;
    "directory": string;
}

export type Tab = any;

export interface TabState {
    "activeTabId": string;
    "tabs": Tab[] | null;
}

export type Variable = NameValue;
