// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";

/**
 * UserSettings matches the Rust UserSettings YAML format.
 */
export interface UserSettings {
    "theme": string;
    "services": models$0.ServiceStub[] | null;
}
